### ISSUE TITLE
adm puede actualizar plazos de una evaluacion sin perder las evaluaciones que ya fueron realizadas por los evaluadores

### ISSUE THREAD

**Issue by Tvallejos** [DCC-CC4401/2019-1-SoftCore-Solutions-T5#22]

**Comment by FearsomeTuna** [comment]
Pass. Aunque esta el mismo bug en que se permite que la fecha de fin sea menor que la fecha de inicio. Sin embargo se le da pass pues no es parte de este requisito especifico.
